### PR TITLE
Chore/deps [patch]

### PR DESCRIPTION
**Pull request by TomPridham**
mostly lint fixes. i did modify the `MockExtension` class to conform to the type

### CODE REVIEW

**Comment by TomPridham** [comment]
what's the best way to test this to make sure it's all working? the only dep was just a minor, so im inclined to believe it works fine but it'd be good to verify

**Comment by brettinternet** [comment]
You should be able to run locally to confirm. When we find time we can add tests as well

**Comment by brettinternet** [comment]
We could probably bump the CI node matrix up from 8, 10, 12 to 10, 12, 14. I believe the linter has an issue with Node 8.

**Comment by brettinternet** [comment]
How does it look when you run it locally?

**Comment by TomPridham** [comment]
Screenshot from 2020-09-30 12-08-24

**Review by brettinternet — APPROVED** [review]

**Pull request merged**
